### PR TITLE
added pdf url handling

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by gnott** [comment]
Quick comment, PDF files are versioned and the file names are reflected there. The cdn.elifesciences.org version of PDF files is old and my planned (delayed) coding updates will actually stop updating that bucket. You might not be done or maybe this is a temporary configuration? In that case you can ignore my comments!

**Comment by lsh-0** [comment]
that is why there are these pull requests, buddy :)

so, api.elifesciences.org is returning the pdf from the cdn - I'm just using it's logic. Is there a different place I should be looking to serve pdf files from other than the cdn? I don't recall seeing any versioned files in there yesterday when I took a quick look.

I'd be grateful if you could give me the requirements to finish this one off.

**Comment by lsh-0** [comment]
ok, we've figured out what you mean. a ticket has been opened to deal with multiple CDNs. that blocks this PR.

**Comment by lsh-0** [comment]
I've confirmed all articles except corrections have a pdf. merging.

**Pull request merged**
