### PR TITLE
Updated elife-article-xml to: 2017-05-13 12:51:00 +0100

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-bot-lax-adaptor-update-elife-article-xml/13/ which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Looks like https://github.com/elifesciences/bot-lax-adaptor/pull/194 didn't help https://ci--alfred.elifesciences.org/job/pull-requests-projects/job/bot-lax-adaptor/job/PR-200/1/console so @lsh-0 you can remove that code if you want.

**Comment by lsh-0** [comment]
it felt like a reach. I'll see if there is some way to wrap these functions in a lock so they get called sequentially

**Comment by lsh-0** [comment]
got a stacktrace here for posterity:
```
07:05:05 ERROR - 2017-05-15 06:05:05,676 - failed to render doc with error: database is locked -- {}
07:05:05 ERROR - 2017-05-15 06:05:05,676 - failed to scrape article -- {"doc": "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/article-xml/articles/elife-22706-v1.xml", "version": 1, "msid": "22706"}
07:05:05 Traceback (most recent call last):
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 575, in main
07:05:05     article_json = render_single(doc, version=version)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 560, in render_single
07:05:05     article_data = postprocess(render(description, [soup], ctx)[0])
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 431, in postprocess
07:05:05     prune
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/et3/render.py", line 21, in doall
07:05:05     item = do(item, seg, ctx)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/et3/render.py", line 13, in do
07:05:05     return segment(item)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 298, in expand_image
07:05:05     return visit(data, pred, fn)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 250, in visit
07:05:05     results[key] = visit(val, pred, fn, coll)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 250, in visit
07:05:05     results[key] = visit(val, pred, fn, coll)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 255, in visit
07:05:05     return [visit(row, pred, fn, coll) for row in data]
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 250, in visit
07:05:05     results[key] = visit(val, pred, fn, coll)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 255, in visit
07:05:05     return [visit(row, pred, fn, coll) for row in data]
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 250, in visit
07:05:05     results[key] = visit(val, pred, fn, coll)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 255, in visit
07:05:05     return [visit(row, pred, fn, coll) for row in data]
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 243, in visit
07:05:05     data = fn(data)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 296, in fn
07:05:05     element = expand_iiif_uri(msid, element, "image")
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/main.py", line 303, in expand_iiif_uri
07:05:05     (width, height) = iiif.basic_info(msid, element[element_type]["uri"].split('/')[-1])
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/iiif.py", line 41, in basic_info
07:05:05     info_data = iiif_info(msid, filename)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/src/iiif.py", line 53, in iiif_info
07:05:05     resp = requests.get(iiif_info_url(msid, filename))
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
07:05:05     return request('get', url, params=params, **kwargs)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
07:05:05     return session.request(method=method, url=url, **kwargs)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 126, in request
07:05:05     **kwargs
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
07:05:05     resp = self.send(prep, **send_kwargs)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 97, in send
07:05:05     response, timestamp = self.cache.get_response_and_time(cache_key)
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests_cache/backends/base.py", line 72, in get_response_and_time
07:05:05     response, timestamp = self.responses[key]
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 163, in __getitem__
07:05:05     return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
07:05:05   File "/ext/jenkins-libraries-runner/workspace/or_PR-200-NK5RMRHYWNU4JKEQRGAS/venv/local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 117, in __getitem__
07:05:05     self.table_name, (key,)).fetchone()
07:05:05 OperationalError: database is locked
```

I could a simple something to just wait a moment and try again tbh. will open a ticket

**Comment by giorgiosironi** [comment]
Merged as on rebuilding it was green.

**Pull request merged**
