### PR TITLE
Feature: replace green with pytest

### PR DESCRIPTION
**Pull request by lsh-0**
fyi @seanwiseman

### CODE REVIEW

**Comment by giorgiosironi** [comment]
:+1: for the direction, `pytest` has lots of plugins e.g. for parallelization and a native JUnit XML result output

**Comment by lsh-0** [comment]
I'm very interested in disabling net access while running tests. If this is successful and then a lax port is successful, there is an old lax branch I want to revisit that is finding and mocking calls the tests are making to AWS

**Comment by lsh-0** [comment]
I'm hoping to spend a few minutes on this today before I sign off. I want to see coverage integration working

**Comment by lsh-0** [comment]
[13 months later]

I have coverage integration working now.

**Pull request merged**
