### PR TITLE
Build on c4.4xlarge/c4.8xlarge

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Corpus generation goes down from 40-45 minutes measured on `develop` to 23-24. We pay double for the hardware, but we almost halve the time we use it, and since it's billed by the minute this should not cost more.

**Comment by giorgiosironi** [comment]
`c4.8xlarge` takes ~11 minutes for the corpus generation, doing a new run to confirm.

**Comment by giorgiosironi** [comment]
Build times are consistent.

**Comment by lsh-0** [comment]
... (you know, I have an actual Castle of Grayskull in a storage box)

**Pull request merged**
