### PR TITLE
Updated elife-article-xml to: 2017-03-18 12:49:17 +0000

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-bot-lax-adaptor-update-elife-article-xml/4/ which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Interesting
```
07:39:39 INFO - 2017-03-20 07:34:28,108 - elife-24052-v1.xml.json => failed
07:39:39 INFO - 2017-03-20 07:34:29,018 - elife-24106-v1.xml.json => failed
07:39:39 INFO - 2017-03-20 07:34:36,351 - elife-22001-v1.xml.json => failed
```
First two are problems with the copyright statement, while the third is on reviewers.

**Comment by gnott** [comment]
Thanks @giorgiosironi  There's an existing ticket for the copyright statements issues, and I opened a new ticket for the reviewing editor role.

**Comment by gnott** [comment]
These may take a day or more, an FYI.

**Comment by giorgiosironi** [comment]
Closing this as outdated, a new one will be opened on Monday branching from the latest `develop`.

**Pull request closed without merging**
