### PR TITLE
Updated elife-article-xml to: 2017-04-29 01:51:41 +0100

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-bot-lax-adaptor-update-elife-article-xml/10/ which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Two different reasons:
```
07:38:36 INFO - 2017-05-01 06:03:09,349 - elife-23172-v2.xml -> elife-23172-v2.xml.json => failed (('Author missing required competingInterests', {'version': 2, 'msid': u'23172'}))
07:38:36 INFO - 2017-05-01 06:05:00,228 - elife-21690-v2.xml -> elife-21690-v2.xml.json => failed (number of available sources less than known sources for u'media2'. missing: webm)
```
23172-v2 needs a silent correction or to be added to the lookup table? While I'm not sure how 21690 got published if it is missing a video format for `media2`?

**Comment by gnott** [comment]
23172 I will make a guess it was ingested prior to the more strict check I added for competing interests. Will check with Production.

21690 The metadata at https://movie-usa.glencoesoftware.com/metadata/10.7554/eLife.21690 has no webm, which is odd. Something we might need to ask Glencoe about.

I'll create some JIRA tickets. Thanks @giorgiosironi

**Comment by giorgiosironi** [comment]
`webm_href` references have appeared in https://movie-usa.glencoesoftware.com/metadata/10.7554/eLife.21690 so I'll do another run of this to see if we get to only 1 invalid.

**Comment by giorgiosironi** [comment]
This shouldn't have passed, as 23172-v2 has not been corrected yet.

**Comment by giorgiosironi** [comment]
We were still allowing for 1 non-generatable article.

**Comment by giorgiosironi** [comment]
Also, I'll do a new pull request to get a more up-to-date elife-article-xml.

**Pull request closed without merging**
