### PR TITLE
Updated elife-tools to: requirements.txt pinned to 876835f6a537f82126ff534f13ba9f18b24e6fa1

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-bot-lax-adaptor-update-elife-tools/88/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by gnott** [comment]
I'm not authorized to merge - not a rush, but I will be unable to deploy any of these parser changes alone.

**Comment by giorgiosironi** [comment]
You have `Write` permissions as part of the `tech` team, but the rules for the `develop` branch are set to only allow administrators to push to it:
https://github.com/elifesciences/bot-lax-adaptor/settings/branch_protection_rules/1721042
I'll relax this now.

**Comment by giorgiosironi** [comment]
Relaxed, as it didn't even apply to `master` but only to `develop`.

**Comment by gnott** [comment]
Thanks kindly @giorgiosironi !

**Pull request merged**
