### PR TITLE
Updated elife-article-xml to: 2020-02-07 17:41:45 +0000

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-bot-lax-adaptor-update-elife-article-xml/157/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by lsh-0** [comment]
re: fixes version of werkzeug

https://github.com/jarus/flask-testing/issues/143

**Comment by lsh-0** [comment]
had a bunch of timeouts as we hammered iiif without a cache. I bet it's also responsible for loggly complaining about hitting out 80% quota for the day.

good to know that iiif still can't survive a complete backfill

**Comment by lsh-0** [comment]
much better result:

```
[2020-02-11T03:37:34.905Z] Input: 13658 JSON articles
[2020-02-11T03:37:34.905Z] Output valid: 13657 JSON articles
[2020-02-11T03:37:34.905Z] Output invalid: 1 JSON articles
[2020-02-11T03:37:34.905Z] Validated green,red,total: 13657,1,13658
[2020-02-11T03:37:34.905Z] No more than 0 articles should be failing validation (with placeholders)
[2020-02-11T03:37:34.905Z] INFO - 2020-02-11 03:36:25,626 - elife-23292-v2.xml.json => failed
```

we still have an invalid article though: 
[bot-lax-validation-failure.log.txt](https://github.com/elifesciences/bot-lax-adaptor/files/4184027/bot-lax-validation-failure.log.txt)

cc @gnott @giorgiosironi

**Comment by lsh-0** [comment]
dedicated werkzeug fix here: https://github.com/elifesciences/bot-lax-adaptor/pull/604

**Comment by gnott** [comment]
The most likely reason I can see for the failure to validate output from `elife-23292-v2.xml` is a figure in the JSON output with a `width: None, height: None`. The particular image in IIIF is https://iiif.elifesciences.org/lax/23292%2Felife-23292-fig5-figsupp1-v2.tif, which is showing a width and height. I attribute the error to being a random glitch getting image dimentions from IIIF. I will re-run the pipeline tests to see if it will pass or repeat the same error.

**Comment by lsh-0** [comment]
>  to being a random glitch getting image dimentions from IIIF.

with the recreation of elife-libraries, the bot-lax caches were recreated as well, putting IIIF under a bit of stress. I'm pretty sure it dropped a number of requests initially. The next run was improved but it's possible that single request failed

**Pull request merged**
