### PR TITLE
Updated elife-article-xml to: 2019-05-31 16:58:45 +0100

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-bot-lax-adaptor-update-elife-article-xml/121/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by gnott** [comment]
Glencoe video naming issue with `elife-26287-v3.xml`. @lsh-0 @giorgiosironi, I'm not sure if we should check in more detail then alert Production? It could be different file naming slipped into the latest version?

**Comment by lsh-0** [comment]
I'll take a look now

**Comment by lsh-0** [comment]
response from glencoe:

```
curl https://movie-usa.glencoesoftware.com/metadata/10.7554/eLife.26287

{
  "video2": {
    "size": 4103800,
    "height": 400,
    "solo_href": "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.26287/video2",
    "video_id": "video2",
    "title": "",
    "uuid": "191d40b8-a02b-417b-9076-5381ec1d4832",
    "flv_href": "https://static-movie-usa.glencoesoftware.com/flv/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video2.flv",
    "doi": "10.7554/eLife.26287.010",
    "source_href": "https://static-movie-usa.glencoesoftware.com/source/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video2.mp4",
    "ogv_href": "https://static-movie-usa.glencoesoftware.com/ogv/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video2.ogv",
    "width": 396,
    "href": "elife-26287-video2.mp4",
    "webm_href": "https://static-movie-usa.glencoesoftware.com/webm/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video2.webm",
    "jpg_href": "https://static-movie-usa.glencoesoftware.com/jpg/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video2.jpg",
    "duration": 51.6,
    "mp4_href": "https://static-movie-usa.glencoesoftware.com/mp4/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video2.mp4",
    "legend": "<div class=\"caption\"><h3 class=\"title\">Explanted larval brain cultured in vitro from 48&#8211;72 hr without 20-hydroxy-ecdysone.</h3><p>Two type II neuroblasts are shown expressing <i>wor-gal4 ase-gal80 UAS-myr:GFP</i> (see Materials&#160;and&#160;methods). Still panels from video shown in <a href=\"#fig3\">Figure 3F</a>, and cell cycle times quantified in <a href=\"#fig3\">Figure 3G</a>.</p></div>"
  },
  "video1": {
    "size": 1055722,
    "height": 720,
    "solo_href": "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.26287/video1",
    "video_id": "video1",
    "title": "",
    "uuid": "8c623ef1-ddee-4114-ac9a-2fdca6503cb2",
    "flv_href": "https://static-movie-usa.glencoesoftware.com/flv/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video1.flv",
    "doi": "10.7554/eLife.26287.009",
    "source_href": "https://static-movie-usa.glencoesoftware.com/source/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video1.mp4",
    "ogv_href": "https://static-movie-usa.glencoesoftware.com/ogv/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video1.ogv",
    "width": 720,
    "href": "elife-26287-video1.mp4",
    "webm_href": "https://static-movie-usa.glencoesoftware.com/webm/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video1.webm",
    "jpg_href": "https://static-movie-usa.glencoesoftware.com/jpg/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video1.jpg",
    "duration": 6.25,
    "mp4_href": "https://static-movie-usa.glencoesoftware.com/mp4/10.7554/136/c3e7e4bae4338f95baf81bfcb98149c492d6eda8/elife-26287-video1.mp4",
    "legend": "<div class=\"caption\"><h3 class=\"title\">Explanted larval brain cultured in vitro from 48&#8211;72 hr with added 20-hydroxy-ecdysone.</h3><p>Two type II neuroblasts are shown expressing <i>wor-gal4 ase-gal80 UAS-myr:GFP</i> (see Materials&#160;and&#160;methods). Still panels from video shown in <a href=\"#fig3\">Figure 3E</a>, and cell cycle times quantified in <a href=\"#fig3\">Figure 3G</a>.</p></div>"
  }
}
```
I was wondering how the article managed to get published. So, we have a cache entry somewhere (end2end?) that needs to be cleared. It stored a successful response once but that isn't true any longer.

I'll also check the xml of the previous articles as well. They need to be referencing 'video' rather than 'media' now

**Comment by lsh-0** [comment]
v1 is a poa so no problems there, but v2 is a vor and has links to 'media' rather than 'video'.

I'll let production know they need to do a silent correction

**Comment by lsh-0** [comment]
> So, we have a cache entry somewhere (end2end?) that needs to be cleared. 

hm. Even if we cleared the cache, then one of the two articles would fail during regeneration. This issue is blocked until the article data is fixed.

**Comment by giorgiosironi** [comment]
The cache entry for this project's tests is probably on `elife-libraries--powerful3`.

**Comment by lsh-0** [comment]
I never linked the production issue I raised: https://github.com/elifesciences/issues/issues/4940

**Comment by lsh-0** [comment]
Glencoe are reporting that everything is looking good now. Re-running the corpus generation and we'll see

**Pull request closed without merging**
