### PR TITLE
Updated elife-tools to: requirements.txt pinned to dacd55fb18885d0462b2266cdd3ba1b11a003aca

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-bot-lax-adaptor-update-elife-tools/40/ which resulted in this pull request.

### CODE REVIEW

**Comment by gnott** [comment]
This will introduce dataId values into citation / references if they are present in the XML. Schema compatible, I'm just unsure how they would look on journal.

**Comment by giorgiosironi** [comment]
Is this ready to merge now? :thinking:

**Comment by gnott** [comment]
I guess so. The inclusion of dataId will be part of the next PR that updates the parser version anyway.

**Comment by giorgiosironi** [comment]
Closing in favor of https://github.com/elifesciences/bot-lax-adaptor/pull/314

**Pull request closed without merging**
