### PR TITLE
Updated api-raml to: 2017-04-12 10:21:18 +0100

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-bot-lax-adaptor-update-api-raml/3/ which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Apparently *this* is the update that enforces IIIF schema, and one of the tests fails. /cc @gnott @thewilkybarkid

**Comment by giorgiosironi** [comment]
Reproduces perfectly on my machine, checking out why.

**Comment by giorgiosironi** [comment]
The fixture of a JSON article is out of date.

**Comment by gnott** [comment]
Good fix @giorgiosironi. This might mean the boxes to have a mandatory id attribute also passes tests and that's very good too.

**Comment by giorgiosironi** [comment]
Ok *now* all 5883 article versions stored here validate with IIIF.

**Pull request merged**
