### PR TITLE
added a simple web interface 

### PR DESCRIPTION
**Pull request by lsh-0**
allows individual articles to be uploaded/generated/validated/deleted

### CODE REVIEW

**Comment by giorgiosironi** [comment]
which port and/or virtual host it will use? (guessing on the lax--prod instance where the code is already deployed)

**Comment by lsh-0** [comment]
not sure - haven't thought that far ahead yet. we'll need to update the formula, possibly password protect things.

**Comment by lsh-0** [comment]
want to add a test or two before I merge this

**Comment by lsh-0** [comment]
added some tests for the flask server, just enough to get us over the 80% coverage mark.

I'm not sure how much time to spend on coverage I want on this until we get some feedback from production as to whether it's useful

**Pull request merged**
