### PR TITLE
added test for expansion of relative urls within inline html

### PR DESCRIPTION
**Pull request by lsh-0**
added breaking test that will pass when the expansion of relative urls is fixed

pinging @giorgiosironi

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
I'm assuming this is related to the current end2end failures (eg https://ci--alfred.elifesciences.org/job/test-journal/279/)?

**Comment by lsh-0** [comment]
yah. there has been some regression and now we have relative urls again in inline html

**Comment by giorgiosironi** [comment]
Yes, but we have rolled back Lax so test-journal should become green again.

**Comment by giorgiosironi** [comment]
Good test by the way :+1:

**Comment by giorgiosironi** [comment]
A bit outdated probably, should be rebased to be tested again.

**Comment by giorgiosironi** [comment]
Looks very outdated and conflicts with `develop`; I'll close, reopen if needed.

**Pull request closed without merging**
