### PR TITLE
Feature: added mkvenv.sh and updated install.sh

### PR DESCRIPTION
**Pull request by lsh-0**
fixes an issue in the 16.04+ lax-formula (python3.5 not available)

### CODE REVIEW

**Comment by giorgiosironi** [comment]
A Glencoe mismatch prevents us from running the full test suite:
```
[2019-03-11T07:30:42.108Z] INFO - 2019-03-11 07:17:27,186 - elife-31481-v2.xml -> elife-31481-v2.xml.json => failed (glencoe doesn't know 'video3', only 'video1, video2')
```

**Comment by gnott** [comment]
Movie metadata has only `video1` and `video2`: https://movie-usa.glencoesoftware.com/metadata/10.7554/eLife.31481

However the article apparently has six videos: https://elifesciences.org/articles/31481/figures

I think something is wrong at Glencoe. It might require contacting them and more investigation into deposits, and maybe check with Production.

**Comment by lsh-0** [comment]
I didn't get to this today, hopefully tomorrow

**Comment by lsh-0** [comment]
in cases like this does Production have a list of tickets they're dealing with I could check first before contacting Glencoe directly?

**Comment by lsh-0** [comment]
I cleared the cache and gave the build a kick. I don't think the results are going to be any different. There may have been a successful cache hit ages ago with just two videos and it's been updated recently, not sure.

I should definitely re-visit the caching that is happening here. On our side we need to invalidate the cache when we see a new version, even though Glencoe is version-less

**Comment by lsh-0** [comment]
Does any one in @elifesciences/production have any insight in to why eLife.31481 only has 2 articles in Glencoe? https://movie-usa.glencoesoftware.com/metadata/10.7554/eLife.31481

Both versions of the article on the website have 6 videos and all are being served up without issues.

I'm contacting Glencoe now, they might have some insight

**Comment by giorgiosironi** [comment]
I'm not sure that tagging @elifesciences/production (a Github team) will result in notifications being sent to that group of people.

**Comment by FAtherden-eLife** [comment]
We received the notification! 

I think we need to check in with our Typesetters. The latest message from Glencoe suggests that they (our typesetters) re-uploaded only two of the 6 videos, which might explain the problem. (they will have previously uploaded the full 6 videos so I imagine that's why they are still displaying online fine). I will ask them to re-upload all 6 videos to Glencoe and send through the article as a silent correction. If my hunch is right, I think that should resolve the issue.

**Comment by FAtherden-eLife** [comment]
Our typesetters have re-uploaded the 6 videos to Glencoe. In the latest email:
```
{
    "succeeded": [
        {
            "doi": "10.7554/eLife.31481",
            "links": [
                "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.31481/video1",
                "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.31481/video2",
                "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.31481/video3",
                "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.31481/video4",
                "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.31481/video5",
                "https://movie-usa.glencoesoftware.com/video/10.7554/eLife.31481/video6"
            ]
        }
    ],
    "failed": [
    ]
}
```
and I've sent through a silent correction for this article.

**Comment by gnott** [comment]
I don't think an article silent correction workflow is required to get these tests to pass. With the correct Glencoe video data available, this library should be able to use the existing XML file and convert it to JSON using it.

**Comment by FAtherden-eLife** [comment]
Thanks for clarifying. I wasn't sure, and since I had to resupply the article in our production system, in order to send it back to our typesetters (so they could (hopefully) correct the Glencoe data), I thought that I may as well also send through a silent correction.

**Comment by gnott** [comment]
I'm going to re-run the tests to see here, because I'm looking at other PRs and one of them look to have failed due to disk space issues.

**Comment by gnott** [comment]
Ah, darn! I should have cleared the Glencoe cache for this article first. I will do that and try the tests again.

**Comment by gnott** [comment]
I cannot clear the cache on that article myself, and I feel like maybe I'm overstepping into this issue. I was thinking it just needed a little nudge. I'm going to bow out now and others can continue it.

**Comment by giorgiosironi** [comment]
The build is running here:
```
/var/lib/jenkins-libraries-runner/workspace/-projects_bot-lax-adaptor_PR-530 on elife-libraries--powerful3
```
(https://alfred.elifesciences.org/job/pull-requests-projects/job/bot-lax-adaptor/job/PR-530/3/ws/)

**Comment by giorgiosironi** [comment]
I was trying to log in to run `./clear-article-glencoe-cache.sh 31481` but the server didn't start, will leave it to @lsh-0.

**Comment by lsh-0** [comment]
> I think we need to check in with our Typesetters. The latest message from Glencoe suggests that they (our typesetters) re-uploaded only two of the 6 videos, which might explain the problem. 

this *is* interesting. I sent an email to glencoe, they might be able to verify the behaviour we're seeing. 

I'll take a look at that `elife-libraries--powerful3` machine and see what is up

**Comment by lsh-0** [comment]
glencoe error has been resolved, kicking build

**Comment by lsh-0** [comment]
bastard

```
INFO - 2019-03-20 02:37:18,132 - elife-31481-v2.xml -> elife-31481-v2.xml.json => failed (glencoe doesn't know 'video3', only 'video1, video2')
```

... glencoe is reporting it has all of the correct deposits now, almost certainly an old cache.

**Pull request merged**
